#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink vim prefs
rm -f $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm -f $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim


if [[ "$OSTYPE" == "darwin"* ]]; then
	source ~/.dotfiles/macos
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
	source ~/.dotfiles/linux
fi

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'