#!/bin/bash

# GNU Linux specific installation comamnds

echo 'Updating repository...'
echo '-----------'
sudo apt update

echo 'Install build essential'
echo '-----------'
sudo apt install build-essential -y

echo 'Install curl'
echo '------------'
sudo apt install curl -y

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
sudo apt install zsh -y
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Symlink zsh prefs
rm -f $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

echo 'Install php'
echo '-----------'
sudo apt install php7.0 -y
sudo apt install php7.1 -y
sudo apt install php7.2 -y
sudo apt install php7.4 -y
sudo apt install php-pear -y
sudo apt install libapache2-mod-php -y
sudo apt install php-mysql -y

echo 'Install composer'
echo '----------------'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer

echo 'Install node'
echo '-----------'
sudo apt install nodejs -y

echo 'Install wget'
echo '------------'
sudo apt install wget -y

echo 'Install httpie'
echo '--------------'
sudo apt install httpie -y

echo 'Install apache2'
echo '-----------'
sudo apt install apache2 -y

echo 'Install imagemagick'
echo '-------------------'
sudo apt install imagemagick -y

echo 'Install imagick'
echo '---------------'
sudo apt install php-imagick -y

echo 'Install xdebug'
echo '--------------'
pecl install xdebug -y

echo 'Install redis'
echo '-------------'
sudo apt install redis-server -y
pecl install redis

echo 'Install mysql'
echo '-------------'
sudo apt install mariadb-server -y

echo 'Install yarn'
echo '------------'
sudo apt install yarn -y

echo 'Install git flow avh'
echo '------------'
sudo apt install git-flow -y

echo 'Install gitk'
echo '------------'
sudo apt install gitk -y
