#!/bin/bash

# macOS specific installation commands

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Symlink zsh prefs
rm -f $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Making Oh My ZSH the default
sudo chsh -s $(which zsh)

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'Install composer'
echo '----------------'
brew install composer

echo 'Install node'
echo '-----------'
brew install node

echo 'Install wget'
echo '------------'
brew install wget

echo 'Install httpie'
echo '--------------'
brew install httpie

echo 'Install php'
echo '-----------'
brew install php@7.2
brew install php@7.4
brew services start php@7.4

echo 'Install xdebug'
echo '--------------'
printf "\n" | pecl install xdebug

echo 'Install redis'
echo '-------------'
brew install redis
brew services start redis
printf "\n" | pecl install redis

echo 'Install mysql'
echo '-------------'
brew install mysql@5.7
brew link mysql@5.7 --force
brew services start mysql@5.7

echo 'Install yarn'
echo '------------'
brew install yarn

echo 'Install git with gitk'
echo '------------'
brew install git

echo 'Install git flow avh'
echo '------------'
brew install git-flow-avh

echo 'Install ack'
echo '------------'
brew install ack

echo 'Install laravel valet'
echo '---------------------'
composer global require laravel/valet
$HOME/.composer/vendor/bin/valet install

echo 'Install laravel installer'
echo '------------'
composer global require laravel/installer

