#!/bin/bash

# macOS specific installation commands

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Symlink zsh prefs
rm -f $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Making Oh My ZSH the default
sudo chsh -s $(which zsh)

echo 'Install composer'
echo '----------------'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'Install node'
echo '-----------'
brew install node

echo 'Install wget'
echo '------------'
brew install wget --overwrite

echo 'Install httpie'
echo '--------------'
brew install httpie

echo 'Install php'
echo '-----------'
brew install php@7.0
brew install php@7.1
brew install php@7.2
brew install php@7.4

echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick

echo 'Install imagick'
echo '---------------'
pecl install imagick

echo 'Install xdebug'
echo '--------------'
pecl install xdebug

echo 'Install redis'
echo '-------------'
brew install redis
brew services start redis
pecl install redis

echo 'Install mysql'
echo '-------------'
brew install mysql
brew services start mysql

echo 'Install sqlite'
echo '-------------'
brew install sqlite

echo 'Install yarn'
echo '------------'
brew install yarn

echo 'Install git flow avh'
echo '------------'
brew install git-flow-avh

echo 'Install gitk'
echo '------------'
brew install gitk

echo 'Install ack'
echo '------------'
brew install ack

echo 'Install laravel valet'
echo '---------------------'
composer global require laravel/valet
valet install

echo 'Install laravel installer'
echo '------------'
composer global require laravel/installer

