#!/bin/bash

echo 'Install php'
echo '-----------'
sudo apt-get install php7.4 -y
sudo apt-get install php7.4-{curl,mbstring,xml,mysql,sqlite3,zip} -y
sudo apt-get install php-pear -y
sudo apt-get install php-dev -y

echo 'Install composer'
echo '----------------'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer

echo 'Install node'
echo '-----------'
sudo apt-get install nodejs -y

echo 'Install wget'
echo '------------'
sudo apt-get install wget -y

echo 'Install httpie'
echo '--------------'
sudo apt-get install httpie -y

echo 'Install xdebug'
echo '--------------'
sudo pecl install xdebug -y

echo 'Install redis'
echo '-------------'
sudo apt-get install redis-server -y
sudo printf "\n" | pecl install redis

echo 'Install mysql'
echo '-------------'
sudo apt-get install mysql-server -y

echo 'Install sqlite'
echo '-------------'
sudo apt-get install sqlite3 -y

echo 'Install yarn'
echo '------------'
sudo apt-get install yarn -y

echo 'Install git flow avh'
echo '------------'
sudo apt-get install git-flow -y

echo 'Install gitk'
echo '------------'
sudo apt-get install gitk -y

echo 'Install xclip'
echo '------------'
sudo apt-get install xclip -y

echo 'Install ack'
echo '------------'
sudo apt-get install ack -y

echo 'Install valet linux'
echo '------------'
composer global require cpriego/valet-linux
$HOME/.composer/vendor/bin/valet install

echo 'Install laravel installer'
echo '------------'
composer global require laravel/installer
