name: Dotfiles Installation

on:
  push:
  workflow_dispatch:

jobs:
  macos_install:
    runs-on: macos-latest
    steps:
      - name: Check out repository code with submodules
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
      
      - name: Make setup script executable
        run: chmod +x ./setup.sh

      - name: Run setup script
        run: ./setup.sh
