name: Dotfiles Installation

on: [push]

jobs:
  linux_install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clone repository into home directory
      run: |
        cd $HOME
        git clone --recurse-submodules https://github.com/claudsonm/dotfiles.git .dotfiles
        cd .dotfiles
    - name: Setup machine
      run: echo "Setup not executed" # bash ./setup.sh

  macos_install:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Clone repository into home directory
      run: |
        cd $HOME
        git clone --recurse-submodules https://github.com/claudsonm/dotfiles.git .dotfiles
        cd .dotfiles
    - name: Setup machine
      run: bash ./setup.sh
